# Generated by Django 4.1.7 on 2023-03-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_alter_animal_options_alter_animal_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto_animal',
            field=models.ImageField(blank=True, null=True, upload_to='animal_imagens/%Y/%m'),
        ),
    ]
