# Generated by Django 4.1.7 on 2023-03-22 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_remove_foto_foto_alter_animal_especie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='foto_animal',
            new_name='imagem',
        ),
    ]
