# Generated by Django 4.2 on 2023-05-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0007_animal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
