# Generated by Django 4.2 on 2023-05-22 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0011_interessados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interessados',
            old_name='id_animal',
            new_name='animal',
        ),
        migrations.RenameField(
            model_name='interessados',
            old_name='id_proprietario',
            new_name='proprietario',
        ),
    ]
