# Generated by Django 4.2 on 2023-05-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0012_rename_id_animal_interessados_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('C', 'Cachorro'), ('G', 'Gato'), ('', '')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status_adocao_animal',
            field=models.CharField(choices=[('A', 'Para Adocao'), ('AD', 'Adotado'), ('', '')], default='A', max_length=255, verbose_name='Status de Adoção do Animal'),
        ),
    ]
