# Generated by Django 4.2 on 2023-05-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0013_alter_animal_especie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status_adocao_animal',
            field=models.CharField(choices=[('P', 'Para Adocao'), ('AD', 'Adotado'), ('', '')], default='A', max_length=255, verbose_name='Status de Adoção do Animal'),
        ),
    ]
