# Generated by Django 4.2 on 2023-05-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0015_alter_animal_status_adocao_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
