# Generated by Django 4.2 on 2023-05-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0016_alter_animal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
