# Generated by Django 4.2 on 2023-05-24 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0018_alter_animal_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
    ]
