# Generated by Django 4.2 on 2023-05-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0019_alter_animal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
    ]
